# Generated by Django 4.2.6 on 2023-10-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoStatus', models.BooleanField(default=False)),
                ('todoName', models.CharField(max_length=200)),
            ],
        ),
    ]
